from pydantic import BaseModel, Field
from typing import Optional


class EmployeeCreate(BaseModel):
    name: str = Field(..., description="Employee's name")
    position: str = Field(..., description="Employee's position")
    email: str = Field(..., description="Employee's email")
    phone: str = Field(..., description="Employee's phone")


class Employee(EmployeeCreate):
    employee_id: Optional[int] = Field(None, description="Employee ID")

    class Config:
        from_attributes = True


class CustomerCreate(BaseModel):
    name: str = Field(..., description="Customer's name")
    email: str = Field(..., description="Customer's email")
    phone: str = Field(..., description="Customer's phone")


class Customer(CustomerCreate):
    customer_id: int = Field(..., description="Customer ID (autogenerated)")

    class Config:
        from_attributes = True


