from pydantic import BaseModel, Field

class OrderDetailCreate(BaseModel):
    order_id: int = Field(..., description="Associated order ID")
    menu_id: int = Field(..., description="Menu item ID")
    quantity: int = Field(..., description="Quantity of the item in the order")

class OrderDetail(OrderDetailCreate):
    order_detail_id: int = Field(..., description="Order detail ID (autogenerated)")

    class Config:
        from_attributes = True




 



